// <auto-generated/>

namespace FuncNet
{

    // Union<string, int>
    // Union<bool, int, string>
    // Union<int, bool, string>
    // Union<int, string, bool>
    // Union<int, string, bool, DateTime>
}